"""change_todo

Revision ID: 1e89a84804a6
Revises: be9a036f7583
Create Date: 2025-01-29 16:36:13.266967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e89a84804a6'
down_revision: Union[str, None] = 'be9a036f7583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 新しいテーブルを作成
    op.create_table(
        'todo_new',
        sa.Column('todo_id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('box', sa.String(200), nullable=False),
        sa.Column('date', sa.DateTime, nullable=False, server_default=sa.func.now()),  # DateTimeに変更
        sa.Column('done', sa.Boolean, default=False, nullable=False)
    )

    # 古いテーブルからデータをコピー
    op.execute('INSERT INTO todo_new (todo_id, box, date, done) SELECT todo_id, box, date, done FROM todo')

    # 古いテーブルを削除
    op.drop_table('todo')

    # 新しいテーブルの名前を元に戻す
    op.rename_table('todo_new', 'todo')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('done', sa.BOOLEAN(), nullable=True))
    op.alter_column('todo', 'date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
