"""create_tables

Revision ID: 2f438095d52a
Revises: 
Create Date: 2025-01-31 16:54:05.383165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f438095d52a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    comment='tagの内容を管理するテーブル'
    )
    op.create_table('todo',
    sa.Column('todo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('box', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('todo_id'),
    comment='todoの内容を管理するテーブル'
    )
    op.create_table('set',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.todo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='todoとtagの関連を設定するテーブル'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set')
    op.drop_table('todo')
    op.drop_table('tag')
    # ### end Alembic commands ###
